### ISSUE TITLE
Breaking Minecraft EULA

### ISSUE THREAD

**Issue by jaydevelopsshit** [Foreheadchann/EquinoxClient#1]
Hey, I know you probably haven't looked at this project in a long while but it violates Mojang's EULA or something that says you can't post any code from Mojang.

**Comment by Foreheadchann** [comment]
i do indeed know, and this project has been abandoned the day it was started, i would delete it but i am extremely lazy.. so either it gets taken down or it stays up (just like 90% of the open source clients on github)

**Comment by jaydevelopsshit** [comment]
Fair
